import { atomWithLocalStorage } from '~/utils/atomWithLocalStorage';
export const localStorageAtoms = {
    autoScroll: atomWithLocalStorage('autoScroll', false),
    showCode: atomWithLocalStorage('showCode', false),
    hideSidePanel: atomWithLocalStorage('hideSidePanel', false),
    modularChat: atomWithLocalStorage('modularChat', true),
    LaTeXParsing: atomWithLocalStorage('LaTeXParsing', true),
    UsernameDisplay: atomWithLocalStorage('UsernameDisplay', true),
    TextToSpeech: atomWithLocalStorage('textToSpeech', true),
    automaticPlayback: atomWithLocalStorage('automaticPlayback', false),
    enterToSend: atomWithLocalStorage('enterToSend', true),
    SpeechToText: atomWithLocalStorage('speechToText', true),
    conversationMode: atomWithLocalStorage('conversationMode', false),
    advancedMode: atomWithLocalStorage('advancedMode', false),
    autoSendText: atomWithLocalStorage('autoSendText', false),
    autoTranscribeAudio: atomWithLocalStorage('autoTranscribeAudio', false),
    decibelValue: atomWithLocalStorage('decibelValue', -45),
    endpointSTT: atomWithLocalStorage('endpointSTT', 'browser'),
    endpointTTS: atomWithLocalStorage('endpointTTS', 'browser'),
    cacheTTS: atomWithLocalStorage('cacheTTS', true),
    voice: atomWithLocalStorage('voice', ''),
    forkSetting: atomWithLocalStorage('forkSetting', ''),
    splitAtTarget: atomWithLocalStorage('splitAtTarget', false),
    rememberForkOption: atomWithLocalStorage('rememberForkOption', true),
    playbackRate: atomWithLocalStorage<number | null>('playbackRate', null),
    saveDrafts: atomWithLocalStorage('saveDrafts', false),
  }